mozilla/dim

.gitignore, dim/config_parser.py, dim/models/tests/base.py, dim/models/tests/not_null.py
chore(): making some tweaks to make the code a bit easier to read
=> chore(): making some tweaks to make the code a bit easier to read

dim/config_parser.py, dim/models/tests/base.py, dim/models/tests/templates/uniqueness.sql.jinja, dim/models/tests/uniqueness.py, dim/test_config.yml, dim_checks/data-monitoring-dev/dummy/active_users_aggregates_v1/dim_checks.yml
Add folder structure and some more clean up
=> create folder structure for sql tests and results

README.md, dim/config_parser.py
=> updated README with execution plan and things that need added

.circleci/config.yml, Dockerfile, Makefile, dim/cli.py, dim/models/dq_checks/base.py, dim/models/dq_checks/templates/not_null.sql.jinja, dim/models/dq_checks/templates/uniqueness.sql.jinja, dim/slack.py, dim/utils.py, pyproject.toml, tests/test_not_null/test_not_null.py, tests/test_uniqueness/test_uniqueness.py
=> fixed final flake8 errors, some descriptions updated

dim/cli.py, dim/models/dim_config.py, dim_checks/alekhya-test-1-322715/monitoring_derived/active_users_aggregates_v1/dim_checks.yml, dim_checks/data-monitoring-dev/dummy/active_users_aggregates_v1/dim_checks.yml
Next step is to add validation logic.
=> dded dim_config model and using that instead

dim/app.py, dim/models/dim_config.py, dim/models/dq_checks/base.py, dim/models/dq_checks/custom_sql_metric.py, dim/models/dq_checks/not_null.py, dim/models/dq_checks/table_row_count.py, dim/models/dq_checks/uniqueness.py, dim/models/dq_checks/value_in_set.py, pyproject.toml, requirements/dev-requirements.in, requirements/dev-requirements.txt, requirements/requirements.in, requirements/requirements.txt, tests/dim_checks/test_not_null/test_not_null.py, tests/dim_checks/test_uniqueness/test_uniqueness.py
=> bug: dim object/config is now correctly loaded

dim/app.py, dim/bigquery_client.py, dim/cli.py, dim/error.py, dim/models/dim_config.py, dim/slack.py, dim/utils.py
=> feat: adding mute cli cmd

dim/bigquery_client.py, dim/cli.py, dim/const.py, dim/utils.py
=> feat: added unmute cmd

tests/cli/test_cli.py
feat: added unit tests for unmute cli cmd
=> feat: added unit tests for unmute cli cmd

Makefile, dim/models/dq_checks/__init__.py, dim/models/dq_checks/template.py, dim/models/dq_checks/templates/template.sql.jinja, docs/guides/adding_a_new_dim_test_type.md
docs: added guide on for adding a new type of dim test/check
=> docs: added guide on for adding a new type of dim test/check

dim_checks/moz-fx-data-shared-prod/org_mozilla_fenix_nightly/baseline_clients_last_seen/dim_checks.yaml
feat: added config for fenix_nightly_baseline_clients_last_seen
=> feat: added config for fenix_nightly_baseline_clients_last_seen

dim/app.py, dim_checks/data-monitoring-dev/monitoring_derived/muted_alerts_v1/dim_checks.yaml, docs/dim_test_types.md
=> feat: now sql field inside params for custom_sql_metric check supports templated values

dim_checks/moz-fx-data-shared-prod/internet_outages/global_outages_v1/dim_checks.yaml
=> feat: added dim_checks for global_outages_v1

dim/app.py, dim/bigquery_client.py, dim/const.py, dim/models/dim_check_type/base.py, dim/utils.py
feat: now persisting processing info in a new BQ table
=> feat: now persisting processing info in a new BQ table

dim/app.py
feat: tweaked slack alert message to make it easier to read
=> feat: tweaked slack alert message to make it easier to read

dim/app.py, dim/utils.py
bug: fixed an error with cost estimation calculation
=> bug: fixed an error with cost estimation calculation

dim/const.py, dim/models/dim_check_type/combined_column_uniqueness.py, dim/models/dim_check_type/templates/combined_column_uniqueness.sql.jinja, dim_checks/data-monitoring-dev/dim/dim_muted_alerts_v1/dim_checks.yaml, docs/dim_test_types.md
=> Feat: added combined column uniqueness check type

dim/app.py, dim/utils.py
instead it will live in a bq view.
=> feat: removed processing to usd conversion logic from dim

dim/app.py
=> bug: removing no-qa from slack alert text

dim/const.py, dim/models/dim_check_type/matches_regex.py, dim/models/dim_check_type/templates/matches_regex.sql.jinja, dim/models/dim_config.py, dim_checks/data-monitoring-dev/dim/dim_muted_alerts_v1/dim_checks.yaml, dim_checks/moz-fx-data-shared-prod/org_mozilla_fenix_nightly/baseline_clients_last_seen/dim_checks.yaml, docs/dim_test_types.md
=> feat: added matches_regex check type

dim/const.py, dim/models/dim_check_type/numeric_values_matches.py, dim/models/dim_check_type/templates/numeric_values_matches.sql.jinja, docs/dim_test_types.md
=> feat: numeric_value_matches dim check added

dim/app.py, dim/cli.py, dim/error.py, tests/cli/test_cli.py
This is to make the dim process exit with a failed status code allowing Airflow tasks to be marked as failed whenever any test fails.
=> feat: added a flag option to run cmd

dim_checks/moz-fx-data-shared-prod/internet_outages/global_outages_v1/dim_checks.yaml
=> feat: added combined_column_uniqueness for internet_outages.global_outages_v1

dim/app.py, dim/models/dim_check_type/base.py, dim/models/dim_check_type/column_length.py, dim/models/dim_check_type/column_sum_not_zero.py, dim/models/dim_check_type/combined_column_uniqueness.py, dim/models/dim_check_type/compare_row_count_to_table.py, dim/models/dim_check_type/custom_sql_metric.py, dim/models/dim_check_type/matches_regex.py, dim/models/dim_check_type/not_null.py, dim/models/dim_check_type/numeric_values_matches.py, dim/models/dim_check_type/table_row_count.py, dim/models/dim_check_type/template.py, dim/models/dim_check_type/templates/column_length.sql.jinja, dim/models/dim_check_type/templates/column_sum_not_zero.sql.jinja, dim/models/dim_check_type/templates/combined_column_uniqueness.sql.jinja, dim/models/dim_check_type/templates/compare_row_count_to_table.sql.jinja, dim/models/dim_check_type/templates/custom_sql_metric.sql.jinja, dim/models/dim_check_type/templates/matches_regex.sql.jinja, dim/models/dim_check_type/templates/not_null.sql.jinja, dim/models/dim_check_type/templates/numeric_values_matches.sql.jinja, dim/models/dim_check_type/templates/table_row_count.sql.jinja, dim/models/dim_check_type/templates/template.sql.jinja, dim/models/dim_check_type/templates/uniqueness.sql.jinja, dim/models/dim_check_type/templates/value_in_set.sql.jinja, dim/models/dim_check_type/uniqueness.py, dim/models/dim_check_type/value_in_set.py, tests/dim_checks/test_uniqueness/test_uniqueness.py
=> feat: some tweaks made and unit test for uniqueness check test sql generation added

dim/const.py, dim/models/dim_check_type/previous_count_avg_within_expected_delta.py, dim/models/dim_check_type/templates/previous_count_avg_within_expected_delta.sql.jinja, dim/models/dim_config.py, dim_checks/moz-fx-data-shared-prod/telemetry_derived/unified_metrics_v1/dim_checks.yaml, docs/dim_test_types.md
=> feat: added a check to compare row count of tested partition to the previous x days average

dim/models/dim_check_type/templates/compare_row_count_to_table.sql.jinja, dim/models/dim_check_type/templates/custom_sql_metric.sql.jinja, dim/models/dim_check_type/templates/matches_regex.sql.jinja, dim/models/dim_check_type/templates/not_null.sql.jinja, dim/models/dim_check_type/templates/numeric_values_matches.sql.jinja, dim/models/dim_check_type/templates/uniqueness.sql.jinja, dim/models/dim_config.py, docs/dim_test_types.md, tests/dim_checks/test_column_length/test_column_length.py, tests/dim_checks/test_combined_column_uniqueness/test_combined_column_uniqueness.py, tests/dim_checks/test_compare_row_count_to_table/test_compare_row_count_to_table.py, tests/dim_checks/test_custom_sql/test_custom_sql.py, tests/dim_checks/test_matches_regex/test_matches_regex.py, tests/dim_checks/test_not_null/test_not_null.py, tests/dim_checks/test_numeric_values_matches/test_numeric_values_matches.py, tests/dim_checks/test_table_row_count/test_table_row_count.py, tests/dim_checks/test_uniqueness/test_uniqueness.py, tests/dim_checks/test_value_in_set/test_value_in_set.py
The table being compared needs to have different partition name
=> feat: modify the table partition for compare_row_count check and unit tests added

dim_checks/moz-fx-data-shared-prod/telemetry/rolling_cohorts/dim_checks.yaml, dim_checks/moz-fx-data-shared-prod/telemetry_derived/rolling_cohorts_v1/dim_checks.yaml
=> feat: added dim config for rolling_cohorts view

dim/app.py, dim/models/dim_check_type/previous_count_avg_within_expected_delta.py, dim/models/dim_check_type/templates/matches_regex.sql.jinja, dim/models/dim_check_type/templates/previous_count_avg_within_expected_delta.sql.jinja, dim_checks/moz-fx-data-shared-prod/org_mozilla_fenix_nightly/baseline_clients_last_seen/dim_checks.yaml, dim_checks/moz-fx-data-shared-prod/telemetry/active_users_aggregates/dim_checks.yaml, dim_checks/moz-fx-data-shared-prod/telemetry/cohort_daily_statistics/dim_checks.yaml, dim_checks/moz-fx-data-shared-prod/telemetry/rolling_cohorts/dim_checks.yaml, dim_checks/moz-fx-data-shared-prod/telemetry/unified_metrics/dim_checks.yaml, dim_checks/moz-fx-data-shared-prod/telemetry_derived/active_users_aggregates_v1/dim_checks.yaml, dim_checks/moz-fx-data-shared-prod/telemetry_derived/cohort_daily_statistics_v1/dim_checks.yaml, dim_checks/moz-fx-data-shared-prod/telemetry_derived/rolling_cohorts_v1/dim_checks.yaml, dim_checks/moz-fx-data-shared-prod/telemetry_derived/unified_metrics_v1/dim_checks.yaml, tests/dim_checks/test_matches_regex/test_matches_regex.py
=> bug: fixed some test definition issues

dim/app.py, dim/slack.py
=> feat: simplified the slack alert to make it easier to read and follow

dim_checks/moz-fx-data-shared-prod/telemetry/active_users_aggregates/dim_checks.yaml, dim_checks/moz-fx-data-shared-prod/telemetry/cohort_daily_statistics/dim_checks.yaml, dim_checks/moz-fx-data-shared-prod/telemetry/rolling_cohorts/dim_checks.yaml, dim_checks/moz-fx-data-shared-prod/telemetry/unified_metrics/dim_checks.yaml
=> bug: regex matches check for country considers ?? also valid

LICENSE
=> docs: LICENSE added to the project

dim_checks/mozdata/focus_android/active_users_aggregates/dim_checks.yaml
=> feat(DENG-913): added dau check for focus_android (release, beta, and nightly channels)

dim_checks/mozdata/focus_ios/active_users_aggregates/dim_checks.yaml
=> feat(DENG-911): added dau check for focus_ios

README.md, dim/slack.py
channel tag should only be included for failed runs
=> channel tag should only be included for failed runs
